parameters:
  # TvManagementBundle actions
  # actionname: id
  # 14xx
  actions:
      site.create:                    1400
      site.create.domain.alias:       1406
      site.list:                      1403
      site.list.domain.alias:         1408
      site.remove:                    1401
      site.remove.domain.alias:       1407
      site.update:                    1402
      site.update.default.language:   1404
      site.update.name:               1405
