services:
    sitemanagement.model:
            class:        BiberLtd\Bundle\SiteManagementBundle\Services\SiteManagementModel
            arguments:    ["@kernel", "default", "doctrine"]
    domain.listener:
            class:        BiberLtd\Bundle\SiteManagementBundle\Listeners\DomainListener
            arguments:    ["@sitemanagement.model", @kernel]
            tags:
                -
                    name: kernel.event_listener
                    method: onKernelRequest
                    event: kernel.request