parameters:
#    biber_ltd_site_management.example.class: BiberLtd\Bundle\SiteManagementBundle\Example

services:
#    biber_ltd_site_management.example:
#        class: %biber_ltd_site_management.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
